const CREDIT_CARD_PAYMENT_METHOD_ID = 1;
const DEBIT_CARD_PAYMENT_METHOD_ID = 2;
const MONEY_PAYMENT_METHOD_ID = 3;

const PAYMENT_METHODS = Object.freeze({
  [CREDIT_CARD_PAYMENT_METHOD_ID]: 'Cartão de crédito',
  [DEBIT_CARD_PAYMENT_METHOD_ID]: 'Cartão de dédito',
  [MONEY_PAYMENT_METHOD_ID]: 'Dinheiro'
});

export {
  PAYMENT_METHODS,
  CREDIT_CARD_PAYMENT_METHOD_ID,
  DEBIT_CARD_PAYMENT_METHOD_ID,
  MONEY_PAYMENT_METHOD_ID
};
